[package]
name = "colourtape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.0"
glutin = "0.28"
egui_glow = "0.16.0"
egui = "0.16.0"
winit = "0.26.1"